apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    io.kompose.service: mongo
spec:
  type: ClusterIP                  # Only reachable inside the cluster (correct for DB)
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo