apiVersion: v1
kind: Service
metadata:
  name: todo-flaskapp
  labels:
    io.kompose.service: todo-flaskapp
spec:
  type: NodePort                   # NodePort = accessible from browser outside cluster
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30080              # You will open this port in browser
  selector:
    io.kompose.service: todo-flaskapp